### ISSUE TITLE
problema pagamento via brcode dinamico santander

### ISSUE THREAD

**Issue by daniloab** [renatofrota/pix-pendencias#12]
ao tentar realizar a leitura de um brcode dinâmico para realizar um pagamento é retornado o seguinte erro:

![image](https://user-images.githubusercontent.com/19939822/101414226-7ace0680-38c4-11eb-8925-751b3505e6af.png)

## reprodução
1 abrir a url https://openpix.com.br/widget/
2 ler o brcode e tentar efetuar o pagamento

A openpix é desenvolvida por nós da entria.com.br e o pagamento a princípio é para ser no valor de R$ 0,01 centavos

**Comment by renatofrota** [comment]
Obrigado pela contribuição, @daniloab.

Porém, o QR em questão tem 2 problemas:

1. Não tem o campo 60 (Merchant City), que é obrigatório no padrão EMV (e o BR Code mantém a exigência). Pode ser apenas um valor curto inócuo, como "Pix", já que será desconsiderado totalmente no arranjo Pix, mas é mandatório.
2. O campo 62-50 deve ser removido. Uma versão antiga do Manual BR Code o citava a título de exemplo. O manual atual não o cita mais - talvez justamente pela confusão que causava ali.
