### ISSUE TITLE
Não aceita GUI (br.gov.bcb.pix) em algum tipo de casing

### ISSUE THREAD

**Issue by rubenskuhl** [renatofrota/pix-pendencias#17]
O parâmetro GUI do EMV é, segundo o manual do BRCode 2.0.1, case-insensitive. Alguns PSPs não aceitam um dos formatos. 

Só aceitavam minúsculas em 07.12.2020:
- Itaú
- C6 Bank

**Comment by renatofrota** [comment]
Obrigado pela colaboração, @rubenskuhl.

Você saberia dizer se o problema se estende ao "Pix Copia e Cola" ou se é exclusivo da leitura do QR Code (com a câmera)?

**Comment by rubenskuhl** [comment]
> Obrigado pela colaboração, @rubenskuhl.
> 
> Você saberia dizer se o problema se estende ao "Pix Copia e Cola" ou se é exclusivo da leitura do QR Code (com a câmera)?

O teste que fiz inicialmente no C6 foi com câmera. Do Itaú não testado.

**Comment by renatofrota** [comment]
Obrigado pelos testes com o C6, @rubenskuhl.
