### ISSUE TITLE
Não verifica se o valor pago em um QR-Code dinâmico confere com o valor da cobrança

### ISSUE THREAD

**Issue by rubenskuhl** [renatofrota/pix-pendencias#19]
Ainda não confirmado se valor saiu ou não da AME Digital e foi para a Gerencianet, mas se confirmado, PSPs com esse problema:
Edit: confirmado que valor integral saiu da AME Digital, então só sobra o #18 mesmo. 
Fechando issue.

**Comment by chiquinhosemx** [comment]
### Detalhamento:

1. Cobrança gerada com valor R$ 0,05 na Gerencianet;
1. String "Copia e Cola" e QR Code gerados com o location da cobrança e sem o TransactionAmount (que é **opcional** no QR dinâmico e deve ser **sempre descartado**);
1. Aplicativo Ame lê o QR/string e aceita alteração do valor de pagamento (ignorando o valor determinado no payload JSON);
1. Enviando o pagamento de **R$ 0,02**, Gerencianet deu baixa na cobrança paga "a menor" e registrou na API o pagamento como tendo sido de **R$ 0,05**;
1. Foi debitado da conta Ame apenas os **R$ 0,02**;

### Processo de devolução foi afetado:

#### Cenário 1:
QR Code de 5 centavos
Valor Pago: 2 centavos
Valor devolvido via app GN: 5 centavos (o valor total creditado)
Valor recebido na Ame após devolução: não foi recebido nenhum valor

#### Cenário 2:
QR Code de 1 centavo
Valor Pago: 1 centavo
Valor devolvido via app GN: 1 centavos (o valor total creditado)
Valor recebido na Ame após devolução: 1 centavo

#### Cenário 3:
QR Code de 2 centavos
Valor Pago: 1 centavos
Valor devolvido via app GN: 1 centavo (o valor realmente pago na Ame)
Valor recebido na Ame após devolução: 1 centavo (igual o valor pago, diferente do valor que foi creditado)

**Comment by renatofrota** [comment]
Obrigado pela colaboração, @rubenskuhl e @chiquinhosemx.

Estou marcando os 2 PSPs envolvidos, já que há problemas a serem tratados em ambos os lados, apesar do problema específico do Ame também constar no issue #18.
