### ISSUE TITLE
Não transaciona Pix com valor inferior a R$ 1,00

### ISSUE THREAD

**Issue by joelemanoel** [renatofrota/pix-pendencias#23]
O PSP só está aceitando PIXs de valor maior ou igual a R$1,00.

PSPs com este problema até 09/12/2020:
- Pagseguro

**Comment by renatofrota** [comment]
Esclarecendo, após discussão no Discord:

PagBank não transaciona abaixo de R$ 1,00 (nem envia, nem recebe).

**Comment by joelemanoel** [comment]
O Pagbank agora passa a transacionar Pix com valor inferir a R$ 1,00
