### ISSUE TITLE
Não aceita QR Code estático gerado de forma autônoma

### ISSUE THREAD

**Issue by renatofrota** [renatofrota/pix-pendencias#26]
Como relatado em: https://github.com/bacen/pix-api/issues/214

* Itaú

O Itaú acata e depois estorna recebimentos Pix via QR Code ou Copia e Cola que contenham valor txid, se este não tiver sido gerado no aplicativo do próprio Itaú.

**Comment by rubenskuhl** [comment]
Isso acontece em PF ou PJ ? Pq a regulação só exige o suporte a QR-Code estático gerado por pessoa física. O de pessoa jurídica é facultativo (com ou sem txid).

**Comment by renatofrota** [comment]
Minha conta PF não aceita.

**Comment by renatofrota** [comment]
Itaú resolveu o problema (ao menos na minha conta, sem que eu os acionasse individualmente).

**Comment by thiagosabino-prog** [comment]
Pessoal descobri o problema no meu caso. O valor que eu estava passando era 1,20 porem ao jogar para string ficava 1.2 e o itaú não aceitava. Então formatei para 1.20 e tudo certo.
