### ISSUE TITLE
QRCodes gerados pela Gerencianet e Juno não são lidos pelo PicPay

### ISSUE THREAD

**Issue by brunoguimaraes** [renatofrota/pix-pendencias#40]
No PicPay, ao tentar ler o QRCode ou inserir o Copia e Cola gerado pela Gerencianet ou Juno, é exibido o erro abaixo:

<img src="https://user-images.githubusercontent.com/10082166/115149480-be870880-a03a-11eb-9e68-48942efd1752.jpeg" width="240"> 

Já verificamos o que foi reportado na issue https://github.com/renatofrota/pix-pendencias/issues/35 e não solucionou, tentamos também com e sem o `Transaction Amount`, `Point of Initiation Method`, `Merchant Name`,  e com `Globally Unique Identifier` maíúsculo ou minúsculo, todas essas alterações não surtiram efeito.

**Comment by renatofrota** [comment]
São QR Codes do ambiente de homologação?

Pode mandar um exemplo?

**Comment by brunoguimaraes** [comment]
Ambiente de produção mesmo... Exemplo:

```
00020101021226880014BR.GOV.BCB.PIX2566qrcodes-pix.gerencianet.com.br/v2/2d036b626b35403a96bf7e9988946a575204000053039865802BR5914GERENCIANET SA6010OURO PRETO62070503***6304C9B3
```

**Comment by renatofrota** [comment]
```
$ curl -s 'https://qrcodes-pix.gerencianet.com.br/v2/2d036b626b35403a96bf7e9988946a57'
{"nome":"cobranca_expirada","mensagem":"A cobrança expirou"}
```

**Comment by brunoguimaraes** [comment]
Aumentei o tempo de expiração:
```
00020101021226880014BR.GOV.BCB.PIX2566qrcodes-pix.gerencianet.com.br/v2/de3fbbf5078f4fac88f16dce05140cc95204000053039865802BR5914GERENCIANET SA6010OURO PRETO62070503***6304759B
```

**Comment by renatofrota** [comment]
Tenho uma suspeita: GN e Juno pode estar barrando os requests do PicPay ao domínio que hospeda os payloads.

Vou contatar a GN pelo Discord deles para ver se eles tem uma posição. Se eles confirmarem que o request tá batendo lá (e eles estão respondendo) aí eu "taggeio" o PicPay e adiciono no #22

**Comment by joelemanoel** [comment]
> Aumentei o tempo de expiração:
> 
> ```
> 00020101021226880014BR.GOV.BCB.PIX2566qrcodes-pix.gerencianet.com.br/v2/de3fbbf5078f4fac88f16dce05140cc95204000053039865802BR5914GERENCIANET SA6010OURO PRETO62070503***6304759B
> ```

Esse seu no Picpay não foi e nem na Juno, mas testei um meu aqui e com o Picpay não deu, mas com a Juno deu certo.

**Comment by renatofrota** [comment]
@joelemanoel a queixa é o PicPay não ler QR Codes dinâmicos gerados na GN ou na Juno (um gerado pela GN ser lido pela Juno não é uma questão). A novidade é o da GN (especificamente o que ele gerou) não ser lido pela Juno. Talvez um erro pontual?

**Comment by joelemanoel** [comment]
> @joelemanoel a queixa é o PicPay não ler QR Codes dinâmicos gerados na GN ou na Juno (um gerado pela GN ser lido pela Juno não é uma questão).

Me passei, acho que é o sono kkkk
Vou testar com o QRCode da Juno no Picpay.

**Comment by joelemanoel** [comment]
> @joelemanoel a queixa é o PicPay não ler QR Codes dinâmicos gerados na GN ou na Juno (um gerado pela GN ser lido pela Juno não é uma questão). A novidade é o da GN (especificamente o que ele gerou) não ser lido pela Juno. Talvez um erro pontual?

O dele tem algumas coisas diferente do meu, "Globally Unique Identifier" está em uppercase e não tem o "Transaction Amount".

**Comment by joelemanoel** [comment]
Em novos testes o PicPay agora passa a aceitar QR Codes gerados pelo Gerencianet. Ainda não testei com Juno por não possuir nenhum QR Code Dinãmico, caso tenham posso testar.
